### ISSUE TITLE
Difference between sched_process_free and sched_process_exit

### ISSUE THREAD

**Issue by Ty-Chen** [brendangregg/perf-tools#101]
Hi, I'm confused what's the differnece between sched_process_free and sched_process_exit. And when I want to listen to a process to ensure that it is fully "terminated" and removed from memory, which is the best choice?

**Comment by Ty-Chen** [comment]
I've solved it by myself. I read the source code and know the difference now.

**Comment by yzhao1012** [comment]
Could you explain here? That would help others to learn the difference, thanks!

**Comment by Eric3495** [comment]
邮件发到~~
