### ISSUE TITLE
what are these messages actually mean?

### ISSUE THREAD

**Issue by code4happylife** [brendangregg/perf-tools#114]
./execsnoop 
Tracing exec()s. Ctrl-C to end.
ERROR: ftrace may be in use by PID 2706686 /var/tmp/.ftrace-lock

**Comment by code4happylife** [comment]
This is a lock file which will be deleted by execsnoop if it exit. Sorry for bothering.
```
### ftrace lock
[[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
```

**Comment by Eric3495** [comment]
邮件发到~~
