### ISSUE TITLE
Feature request: tagged git releases for packagers

### ISSUE THREAD

**Issue by troyengel** [brendangregg/perf-tools#22]
I would like to package tagged, numbered releases of perf-tools for Arch; we have a -git package, but that requires continual manual updating by the end user. Would you be willing to git tag releases so that we can grab github.com generated tarballs from the releases/ page? I'm sure this would assist other distributions in packaging "stable" as well...

**Comment by brendangregg** [comment]
Ok, having hit this myself I really need to do this. I'll push v1.0.

**Comment by brendangregg** [comment]
Done! v1.0 pushed.

**Comment by troyengel** [comment]
Thank you. :)  https://aur.archlinux.org/packages/perf-tools/
