### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by posix4e** [brendangregg/perf-tools#25]
This command works when I run with sudo, but If I don't have permissions I get

posix4e@posix4e-P27GV2:~$ perf stat -e 'ext4:*' -a
invalid or unsupported event: 'ext4:*'
Run 'perf list' for a list of valid events

 usage: perf stat [<options>] [<command>]

    -e, --event <event>   event selector. use 'perf list' to list available events

Anyway to make this give a sign to a user that they should enable permissions

**Comment by GHugo** [comment]
I think it is a `perf` issue, not one of a script of this repository. Besides, there is already a check inside scripts to see if permissions are good.

If you really want to notify this as a bug (more a feature enhancement), I think you should consider raising the kernel mailing list.

**Comment by scotte** [comment]
That could definitely be clearer, but the previous comment is correct - that's an issue in the underlying perf command, not this collection of things built on perf and ftrace.
