### ISSUE TITLE
uprobe fails to work when a library used by a binary is present in different locations.

### ISSUE THREAD

**Issue by RavikumarTulugu** [brendangregg/perf-tools#51]
uprobe fails to work when a library used by a binary is present in different locations. In my case, it is libc which was present at 3 different locations. The fix is to choose one of them and proceed, I am pasting the line here. 
 
 function set_path {
145         name=$1
146
147         path=$(which $name)
148         if [[ "$path" == "" ]]; then
149                 path=$(ldconfig -v 2>/dev/null | awk -v lib=$name '
150                     $1 ~ /:/ { sub(/:/, "", $1); path = $1 }
151                     { sub(/\..*/, "", $1); }
152                     $1 == lib { print path "/" $3 }')
153                 if [[ "$path" == "" ]]; then
154                         die "ERROR: segment \"$name\" ambiguous." \
155                             "Program or library? Try a full path."
156                 fi
157         fi
**158         path=$(echo $path | cut -f2 -d" ")**
159         if [[ ! -x $path ]]; then
160                 die "ERROR: resolved \"$name\" to \"$path\", but file missing"
161         fi
162 }

**Comment by RavikumarTulugu** [comment]
This is a temporary hack but fixes our issue. Thanks

**Comment by vanhauser-thc** [comment]
this patch should work better as it also does not require exec permissions for libraries which are unnecessary:

--- a/user/uprobe
+++ b/user/uprobe
@@ -146,18 +146,21 @@ function set_path {
        name=$1

        path=$(which $name)
+       noexec=
        if [[ "$path" == "" ]]; then
                path=$(ldconfig -v 2>/dev/null | awk -v lib=$name '
                    $1 ~ /:/ { sub(/:/, "", $1); path = $1 }
                    { sub(/\..*/, "", $1); }
-                   $1 == lib { print path "/" $3 }')
+                   $1 == lib { print path "/" $3 }' | tail -n 1)  # can have several libraries as a result
                if [[ "$path" == "" ]]; then
                        die "ERROR: segment \"$name\" ambiguous." \
                            "Program or library? Try a full path."
+               else
+                       noexec=true # libraries do not need the exec permission
                fi
        fi

-       if [[ ! -x $path ]]; then
+       if [[ -z "$noexec" && ! -x "$path" ]]; then
                die "ERROR: resolved \"$name\" to \"$path\", but file missing"
        fi
 }
