### ISSUE TITLE
funcslower: -p filters on thread id and not process id

### ISSUE THREAD

**Issue by goldshtn** [brendangregg/perf-tools#53]
As always with the kernel-colored glasses, the -p switch in some tools uses `set_ftrace_pid`, which is the kernel pid notion -- user thread id. So tracing a process with multiple threads using the -p switch only traces the first thread. I've run into this with funcslower but I assume it affects additional tools as well. 

I can submit a PR that fixes this by parsing the thread ids from /proc/PID/task, or by parsing ps output. Thoughts?

**Comment by goldshtn** [comment]
@brendangregg Thoughts?

**Comment by brendangregg** [comment]
Oh, right. Sounds like we need a -p for PID and -somethingelse for TID (kernel PID). -t/-T is often taken for timestamps (-k then, for kernel thread ID?). Both tools and man pages need updating.

I'd look it up the TIDs from /proc/PID/task.

**Comment by goldshtn** [comment]
In BCC tools we typically used -L for thread id. I'll go with that for consistency I think.
