### ISSUE TITLE
perf script doesn't print the entire stack trace

### ISSUE THREAD

**Issue by huang195** [brendangregg/perf-tools#68]
After collecting perf trace using `perf record -e 'raw_syscalls:sys_enter' --call-graph dwarf,4096`, I use `perf script` to look at the collect data. In most part, it is as expected. However, one issue is that my application binary has symbols stripped. I noticed that whenever `perf script` cannot resolve the symbol of an item on the stack, it stops printing the stack. I don't see an option that says keep printing stack trace even if you cannot resolve a symbol. Did I miss something or is this by design?

**Comment by brendangregg** [comment]
If that's true it sounds like a perf(1) bug. Please raise on the perf-users mailing list.
