### ISSUE TITLE
Not able to generate Flame graphs for Java Apps

### ISSUE THREAD

**Issue by sattishv** [brendangregg/perf-tools#70]
Hi Brendan,

We encountered  the below errors while trying to generate the flame graphs from the host.
After successful perf record we invoked perf script command on perf.data
perf script | ./stackcollapse-perf.pl > out.perf-folded got the below errors. How could we overcome these errors. I believe few are related perfdata file not available in host since it resides in container. This is a multi container env.

Failed to open /tmp/perf-12964.map, continuing without symbols
Failed to open /tmp/perf-20444.map, continuing without symbols
Failed to open /lib/x86_64-linux-gnu/libpthread-2.23.so, continuing without symbols
Failed to open /x/web/LIVE/keymakeragent/keymakeragent/infra/lib/linux_x86_py27/_faststat.so, continuing without symbols
Failed to open /x/opt/pp/bin/python2.7, continuing without symbols
Failed to open /x/web/LIVE/keymakeragent/keymakeragent/infra/lib/linux_x86_py27/greenlet.so, continuing without symbols
Failed to open /applicationpackages/manifests/active/JDK/cronus/scripts/jdk1.8.0_60/jre/lib/amd64/server/libjvm.so, continuing without symbols
Failed to open /tmp/perf-29726.map, continuing without symbols
Failed to open /applicationpackages/manifests/active/JDK/cronus/scripts/jdk1.8.0_60/jre/lib/amd64/libnet.so, continuing without symbols
Failed to open /lib/x86_64-linux-gnu/libc-2.23.so, continuing without symbols
Failed to open /tmp/perf-5808.map, continuing without symbols
Failed to open /tmp/perf-28806.map, continuing without symbols
Failed to open /lib/ld-musl-x86_64.so.1, continuing without symbols
Failed to open /tmp/perf-25990.map, continuing without symbols
Failed to open /lib/libpthread-2.5.so, continuing without symbols
Failed to open /lib/libc-2.5.so, continuing without symbols
Failed to open /tmp/perf-14795.map, continuing without symbols
Failed to open /applicationpackages/manifests/active/JSW/cronus/scripts/JSW/bin/wrapper, continuing without symbols
Failed to open /tmp/perf-22375.map, continuing without symbols
Failed to open /tmp/perf-14695.map, continuing without symbols
Failed to open /usr/bin/ppregistrator, continuing without symbols
Failed to open /x/web/LIVE/keymakeragent/keymakeragent/infra/lib/linux_x86_py27/gevent/core.so, continuing without symbols
Failed to open /tmp/perf-14639.map, continuing without symbols
Failed to open /tmp/perf-23526.map, continuing without symbols
Failed to open /tmp/perf-8628.map, continuing without symbols
Failed to open /applicationpackages/manifests/active/JDK/cronus/scripts/jdk1.8.0_60/jre/lib/amd64/libjava.so, continuing without symbols
Failed to open /usr/lib/libstdc++.so.6.0.8, continuing without symbols
Failed to open /x/web/LIVE/caldaemon/caldaemon, continuing without symbols
Failed to open /tmp/perf-10390.map, continuing without symbols
Failed to open /lib/librt-2.5.so, continuing without symbols
Failed to open /tmp/perf-3844.map, continuing without symbols
no symbols found in /bin/dash, maybe install a debug package?
Failed to open /applicationpackages/manifests/active/JDK/cronus/scripts/jdk1.8.0_60/jre/lib/amd64/libnio.so, continuing without symbols
Failed to open /x/opt/pp/lib/python2.7/lib-dynload/select.so, continuing without symbols
Failed to open /x/opt/pp/lib/python2.7/lib-dynload/time.so, continuing without symbols
Failed to open /applicationpackages/manifests/active/JDK/cronus/scripts/jdk1.8.0_60/jre/lib/amd64/libmanagement.so, continuing without symbols
Failed to open /usr/bin/socat, continuing without symbols
Failed to open /x/opt/pp/lib/python2.7/lib-dynload/_socket.so, continuing without symbols

**Comment by goldshtn** [comment]
Which perf version is this? In Linux 4.13 perf was augmented with basic namespace traversal support, so it can automatically enter the container's namespace to find symbols for your application binaries, shared libraries, and the /tmp/perf-PID.map files.

**Comment by sattishv** [comment]
Hi Thanks for the response.  

We use perf version 4.4.87

Sattish.

**Comment by goldshtn** [comment]
All right, well, that version of perf doesn’t support traversing
namespaces. You’d need to work pretty hard to get things to work — you need
to manually copy the /tmp/perf-pid.map file to the host and rename it so
that the pid matches the host pid, you need to get perf access to the
executable and .so files in the container, etc.

Perhaps you can try building a newer version of perf from source?

**Comment by brendangregg** [comment]
Thanks Sasha for the comments. Closing.
