### ISSUE TITLE
cachestat can't work on kernel 3.16 

### ISSUE THREAD

**Issue by cobblau** [brendangregg/perf-tools#90]
I am trying to run `cachestat` with `./cachestat 5` but it fails with following output   
```
Counting cache functions... Output every 5 seconds.
./cachestat: line 115: function_profile_enabled: Permission denied
ERROR: enabling function profiling. Have CONFIG_FUNCTION_PROFILER? Exiting.
``` 
The kernel version is 
```
Linux version 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03)
```
And there isn't any file named `function_profile_enabled` in `/sys/kernel/debug/tracing` directory.

Is there any solutions for this problem?   
Thanks a lot!

**Comment by scotte** [comment]
Did you try what the error message said regarding CONFIG_FUNCTION_PROFILER? Also documented at https://github.com/brendangregg/perf-tools#ftrace

**Comment by xiaochazuo** [comment]
meet the same question and cant solve it

**Comment by brendangregg** [comment]
Ask your kernel distro to set CONFIG_FUNCTION_PROFILER=y.
